scss:
  enabled: true
  config_file: .scss-lint.yml

ruby:
  config_file: .rubocop.yml

javascript:
  enabled: false
  ignore_file: .javascript_ignore

slim-lint:
  enabled: true
  config_file: .slim-lint.yml

slim:
  enabled: true
  config_file: .slim-lint.yml
