
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/schema.rb"
    - "db/seeds/**/*"
    - "db/migrate/**/*"
    - "config/initializers/devise.rb"
  UseCache: false
  DisabledByDefault: false

# Linting #

Lint/UnusedMethodArgument:
  Enabled: false

###################### Metrics ####################################

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - "features/**/*"
  Max: 15

Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - "features/renalware/**/*"
    - "features/step_definitions/**/*"
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  Max: 20
  Exclude:
    - "features/**/*"

Metrics/ModuleLength:
  Enabled: true
  Max: 100
  Exclude:
    - "features/**/*"

# ##################### Rails ##################################

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Validation:
  Enabled: false

# ################## Style #################################

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: true
  Exclude:
    - "features/**/*"
    - "config/**/*"

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - features/**/*
  Enabled: true

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Style/WhenThen:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/Alias:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MultilineArrayBraceLayout:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/GuardClause:
  Enabled: false
