
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "db/schema.rb"
    - "db/seeds/**/*"
    - "db/migrate/**/*"
    - "config/initializers/devise.rb"
  UseCache: false
  DisabledByDefault: false

# Linting #

Lint/UnusedMethodArgument:
  Enabled: false

###################### Metrics ####################################

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - "features/**/*"
  Max: 20

Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - "features/renalware/**/*"
    - "features/step_definitions/**/*"
  Enabled: true

Metrics/MethodLength:
  Enabled: true
  Max: 30

Metrics/ModuleLength:
  Enabled: true
  Max: 250

# ##################### Rails ##################################

Rails/ActionFilter:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Validation:
  Enabled: false

# ################## Style #################################

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: true
  Exclude:
    - "features/**/*"
    - "config/**/*"

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - features/**/*
  Enabled: true

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Style/SymbolProc:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/Alias:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/MultilineArrayBraceLayout:
  Enabled: false

Style/EachWithObject:
  Enabled: false
