scss_files: "app/assets/stylesheets/**/*.scss"

linters:
  StringQuotes:
    enabled: false
  PropertySortOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: true
  LeadingZero:
    enabled: false
  HexNotation:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
