linters:
  StringQuotes:
    enabled: false
  PropertySortOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  LeadingZero:
    enabled: false
  HexNotation:
    enabled: false
  QualifyingElement:
    enabled: false
