<%
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip -r features/stories"
wip_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --tags @wip:3 --wip -r features/stories"
%>
default: <%= std_opts %> -r features/php/support -r features/php
php: <%= std_opts %> -r features/php/support -r features/php
php_wip: <%= wip_opts %> -r features/php/support -r features/php
ruby: <%= std_opts %> -r features/ruby/support -r features/ruby
ruby_wip: <%= wip_opts %> -r features/rubysupport -r features/ruby