default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: renalware_development
  host: localhost
  username: postgres
  password: pass

test:
  <<: *default
  database: renalware_test
  host: localhost
  username: postgres
  password: pass

staging:
  url: <%= ENV['DATABASE_URL'] %>
