super_admin:
  - Renalware::User
  - Renalware::Role
admin:
  - Renalware::Drug
  - Renalware::DrugType
  - Renalware::EdtaCode
  - Renalware::EventType
  - Renalware::MedicationRoute
  - Renalware::ModalityCode
  - Renalware::OrganismCode
  - Renalware::PrdCode
